/* 
 *  Subnet Manager – Java OO en Gegevens Banken Project
 */
package GUI;

import DatabaseConnection.DatabaseUtil;
import Localization.Localizer;
import Logic.SubnetHelper;
import Objects.Address;
import Objects.HostAddress;
import Objects.Subnet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author louisdhauwe
 */
public class NetworksPanel extends javax.swing.JPanel {

    /**
     * Creates new form NetworksPanel
     */
    public NetworksPanel() {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(10);
        noSubnetsLbl.setText(Localizer.NO_SUBNETS);
        addSubnetBtn.setText(Localizer.ADD_NEW_SUBNET);
        
        subnetsContainerPanel1.listener = new UpdateListener() {

            @Override
            public void update() {
                checkIfNoSubnets();

            }
        };
        
        // Java 8 Lamda expression:
//        subnetsContainerPanel1.listener = () -> {
//            checkIfNoSubnets();
//        };

    }
    
    /**
     * Will set noSubnetsLbl visible if no subnets are in memory
     * otherwise invisible
     */
    public void checkIfNoSubnets() {
        if (DatabaseUtil.getInstance().getSubnets().length > 0) {
            noSubnetsLbl.setVisible(false);
        } else {
            noSubnetsLbl.setVisible(true);
        }
    }
    
    /**
     * Updates UI (call when data changes)
     */
    public void update() {
        subnetsContainerPanel1.updateData();
        checkIfNoSubnets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        subnetsContainerPanel1 = new GUI.SubnetsContainerPanel();
        addSubnetBtn = new javax.swing.JButton();
        noSubnetsLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 153));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMinimumSize(new java.awt.Dimension(960, 282));
        setPreferredSize(new java.awt.Dimension(960, 620));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(subnetsContainerPanel1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        addSubnetBtn.setBackground(new java.awt.Color(255, 255, 204));
        addSubnetBtn.setText("Voeg subnet toe");
        addSubnetBtn.setAlignmentX(0.5F);
        addSubnetBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addSubnetBtn.setDoubleBuffered(true);
        addSubnetBtn.setFocusable(false);
        addSubnetBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addSubnetBtn.setMaximumSize(new java.awt.Dimension(32000, 18));
        addSubnetBtn.setMinimumSize(new java.awt.Dimension(0, 18));
        addSubnetBtn.setRequestFocusEnabled(false);
        addSubnetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubnetBtnActionPerformed(evt);
            }
        });
        add(addSubnetBtn, java.awt.BorderLayout.PAGE_END);

        noSubnetsLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        noSubnetsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noSubnetsLbl.setText("Er zijn geen subnetten, open een database of maak een nieuw subnet aan");
        add(noSubnetsLbl, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void addSubnetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubnetBtnActionPerformed
        
        String name = JOptionPane.showInputDialog(Localizer.ADD_NEW_SUBNET_NAME);
        if (name == null) return;
        
        while (!SubnetHelper.isValidSubnetNameForSubnet(name, null)) {    
     
            name = (String)JOptionPane.showInputDialog(null, Localizer.NAME_NOT_VALID,
            Localizer.ERROR, JOptionPane.ERROR_MESSAGE, null, null, name);

            if (name == null) return;

        }
        
        String networkAddress = JOptionPane.showInputDialog(Localizer.ADD_NEW_SUBNET_NETWORK_ADDRESS.replace("%@", name));
        if (networkAddress == null) return;
        while (true) {    
            try {
                SubnetHelper.isValidNetworkAddress(networkAddress, null);
            } catch (Exception e) {
                networkAddress = (String)JOptionPane.showInputDialog(null, e.getMessage(),
                Localizer.ERROR, JOptionPane.ERROR_MESSAGE, null, null, networkAddress);
                if (networkAddress == null) return;
                continue;
            }
            if (networkAddress == null) return;
            break;
        }
        
        String subnetmask = JOptionPane.showInputDialog(Localizer.ADD_NEW_SUBNET_SUBNETMASK.replace("%@", name));
        if (subnetmask == null) return;

        while (!SubnetHelper.isValidSubnetMask(subnetmask)) {       
            
            subnetmask = (String)JOptionPane.showInputDialog(null, Localizer.SUBNETMASK_NOT_VALID,
            Localizer.ERROR, JOptionPane.ERROR_MESSAGE, null, null, subnetmask);
            
            if (subnetmask == null) return;
            
        }

        ArrayList<HostAddress> h = new ArrayList<>();
        
        Address a1 = SubnetHelper.addressFromString(networkAddress);
        Address a2 = SubnetHelper.addressFromString(subnetmask);

        Subnet s = new Subnet(name, a1, a2, h);
        
        DatabaseUtil.getInstance().addSubnet(s);
        
        update();
        
    }//GEN-LAST:event_addSubnetBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubnetBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel noSubnetsLbl;
    private GUI.SubnetsContainerPanel subnetsContainerPanel1;
    // End of variables declaration//GEN-END:variables
}
